In [25]:
aList = ["John",33,"Toronto",True]
print(aList)

['John', 33, 'Toronto', True]


In [23]:
aList = ["Mahasiswa","Habibiardaffenzy",2021071031,"Informatika","DAA","14-09-22","upj",True]
print(aList)

['Mahasiswa', 'Habibiardaffenzy', 2021071031, 'Informatika', 'DAA', '14-09-22', 'upj', True]


In [29]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[3]

'Yellow'

In [72]:
bin_alist=["Mahasiswa","Habibiardaffenzy",2021071031,"Informatika","DAA","14-09-22","upj",True]
bin_alist[2]

'2021071031'

In [34]:
bin_alist[2]

2021071031

In [35]:
bin_alist[6]

'upj'

In [81]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[0:2]

('Red', 'Green')

In [40]:
bin_alist[2:4]

[2021071031, 'Informatika']

In [59]:

for aColor in bin_colors:
  print(aColor + "Square")

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [76]:
for String in bin_alist:
  print(String ,"upj")

Mahasiswa upj
Habibiardaffenzy upj
2021071031 upj
Informatika upj
DAA upj
14-09-22 upj
upj upj
True upj


In [87]:
bin_colors[2:]

('Blue', 'Yellow')

In [90]:
UPJ=('Universitas Pembangunan Jaya')
UPJ[0:]

'Universitas Pembangunan Jaya'

In [93]:
#Nested Tuple
nested_tuple = ([100],[200,400,600],[300],[400,800])
print(nested_tuple)

([100], [200, 400, 600], [300], [400, 800])


In [97]:
bin_colors ={"manual_color": "Yellow","approved_color": "Green","refused_color": "Red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [100]:
bin_colors.get('approved_color')

'Green'

In [105]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [108]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [111]:
print : red)
{'dandelions', 'fire hydrant', 'blood', 'rose', 'leaves'}
yellow&red
{'fire hydrant'}

SyntaxError: ignored

In [119]:
import pandas as pd
df = pd.DataFrame([
['1', 'Fares', 32, True],
['2', 'Elena', 23, False],
['3', 'Steven', 40, True]])

df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [122]:
df[['name','age']]
name age
0 Fares 32
1 Elena 23
2 Steven 40

df.iloc[:,3]
0 True
1 False
2 True

SyntaxError: ignored

In [134]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
[[11 12 13]
[21 22 23]
[31 32 33]]

print(type(myMatrix))
  <class 'numpy.ndarray'>


SyntaxError: ignored